using System.Collections.Generic;
using System.IO;
using UnityEngine;

public class AssetBundleConfig
{
	public const bool StaticResourceDefault = true;

	private static string CachedBundleDirectory = string.Empty;

	public static string BundleConfigScene
	{
		get
		{
			return "Assets/Scenes/BundleBuildConfig.unity";
		}
	}

	public static string BundleDirectory
	{
		get
		{
			if (string.IsNullOrEmpty(CachedBundleDirectory))
			{
				CachedBundleDirectory = Path.Combine(Application.streamingAssetsPath, "AssetBundles/");
			}
			return CachedBundleDirectory;
		}
	}

	public static string DataBundlePrefabPath
	{
		get
		{
			return "Assets/Content/DataBundlePrefab.prefab";
		}
	}

	public static string BundleBuildLogPath
	{
		get
		{
			return "BundleBuildLog.txt";
		}
	}

	public static Dictionary<string, string> FileNameReplacementStrings
	{
		get
		{
			Dictionary<string, string> dictionary = new Dictionary<string, string>();
			dictionary.Add(" ", "_");
			dictionary.Add("/", "_");
			dictionary.Add("@", "_");
			return dictionary;
		}
	}

	public static string BuildDirectoryConfigFilePath
	{
		get
		{
			return "Assets/Game/Config/BundlePathConfig.txt";
		}
	}

	public static string BundleFileExtension
	{
		get
		{
			return ".unity3d";
		}
	}

	public static string ManifestFileName
	{
		get
		{
			return "Manifest.txt";
		}
	}

	public static string PersistentErrorFileName
	{
		get
		{
			return "PersistentError.txt";
		}
	}

	public static string TempFilePrefix
	{
		get
		{
			return "Temp_";
		}
	}

	public static string CustomAssetBuildPath
	{
		get
		{
			return "Assets/Content/";
		}
	}

	public static string CustomAssetFileExtension
	{
		get
		{
			return ".asset";
		}
	}

	public static string BundleAssetInfoName
	{
		get
		{
			return "BundleAssetInfo.hashtable";
		}
	}

	public static string BundleAssetList
	{
		get
		{
			return "BundleAssetInfo.assetlist";
		}
	}

	public static string DataBundleName
	{
		get
		{
			return "DataBundle.hashtable";
		}
	}

	public static string DataBundleStringList
	{
		get
		{
			return "DataBundle.stringlist";
		}
	}

	public static string VersionKey
	{
		get
		{
			return "UnityVersion";
		}
	}

	public static string ManifestStartTag
	{
		get
		{
			return "<AssetBundleManifest>";
		}
	}

	public static string ManifestLineValueSeperator
	{
		get
		{
			return "<LVS>";
		}
	}

	public static string AutogeneratedObjectName
	{
		get
		{
			return "#Autogenerated#";
		}
	}

	public static bool UncompressedLocalAssetBundles
	{
		get
		{
			return true;
		}
	}

	public static string BundleDataPath
	{
		get
		{
			return Application.streamingAssetsPath;//(!AJavaTools.Properties.IsBuildGoogle()) ? (AJavaTools.GameInfo.GetExternalFilesPath() + "/BundleData") : AJavaTools.GameInfo.GetFilesPath();
		}
	}

	public static bool ForceUpdateDataBundle
	{
		get
		{
			if (Debug.isDebugBuild)
			{
				return true;
			}
			string @string = PlayerPrefs.GetString(DataBundleRuntime.DataBundleAppVersionPrefsKey, string.Empty);
			string version = GeneralConfig.Version;
			return !string.Equals(@string, version);
		}
	}
}
